
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { angleToRadian } from '../../utils/angle'

export function ChairModel(props) {
  const { nodes, materials } = useGLTF('/models/ikea_markus_office_chair.glb')
  return (
    <group dispose={null} scale={0.038} rotation={[0, angleToRadian(135), 0]} position={[-0.5,0,3]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_3.geometry}
              material={materials.IkeaChairT}
              position={[0.049, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_4.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_5.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_6.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_7.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_8.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_9.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_10.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_11.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_12.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_13.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_14.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_15.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_16.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_17.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_18.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_19.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_20.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_21.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_22.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_23.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_24.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_25.geometry}
              material={materials.IkeaChairMesh}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_26.geometry}
              material={materials.IkeaChairMesh}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_27.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_28.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_29.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_30.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_31.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_32.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_33.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_34.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_35.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_36.geometry}
              material={materials.IkeaChairT}
              position={[0.049, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_37.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_38.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_39.geometry}
              material={materials.IkeaChairT}
              position={[0.049, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_40.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_41.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_42.geometry}
              material={materials.IkeaChairT}
              position={[0.049, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_43.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_44.geometry}
              material={materials.IkeaChairT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_45.geometry}
              material={materials.IkeaChairT}
              position={[0.049, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_46.geometry}
              material={materials.IkeaChairT}
              position={[53.851, 0, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/ikea_markus_office_chair.glb')
