/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LUST Man (https://sketchfab.com/Lustman)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/notes-979567859cf14970bcee47938db9f1f3
Title: Notes
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function ClipboardModel(props) {
  const { nodes, materials } = useGLTF('/models/notes.glb');
  return (
    <group {...props} dispose={null}position={[-1.5, 2.93, 0]} rotation={[0, -Math.PI / 4, 0]} scale={0.15}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.None}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/notes.glb');
