/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DARSH (https://sketchfab.com/DarshyBarshy)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/simple-basic-office-work-desk-5ee822265d714be99dcc5f5091db669c
Title: Simple basic office / work desk
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { angleToRadian } from '../../utils/angle';

export function DeskModel(props) {
  const { nodes, materials } = useGLTF(
    '/models/simple_basic_office__work_desk.glb'
  );
  return (
    <group {...props} dispose={null}>
      <group position={[1, 2.6, 1]} scale={1.25} rotation={[0,-angleToRadian(30),0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['Material.002']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/simple_basic_office__work_desk.glb');

// export function DeskModel(props) {
//   const { nodes, materials } = useGLTF('/models/lowpoly_desk_and_monitor.glb');
//   return (
//     <group  dispose={null}>
//       <group scale={0.038} position={[0, 0, 2]} rotation={[0, -angleToRadian(45), 0]}>
//         <group position={[-8.412, 40.581, -48.956]}>
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Table1_Palette_0.geometry}
//             material={materials.Palette}
//           />
//           {/* <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Headphones_Palette_0.geometry}
//             material={materials.Palette}
//             position={[59.264, 60.42, -33.211]}
//             rotation={[-Math.PI, -0.96, -Math.PI]}
//             scale={[0.44, 1, 1]}
//           /> */}
//           {/* <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Triple_Monitor_Palette_0.geometry}
//             material={materials.Palette}
//             position={[-0.251, 54.356, -43.196]}
//           /> */}
//           {/* <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.White_Keyboard_Palette_0.geometry}
//             material={materials.Palette}
//             position={[-40.064, 38.591, 29.178]}
//           /> */}
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.White_Mouse_Palette_0.geometry}
//             material={materials.Palette}
//             position={[55.287, 39.724, 33.793]}
//           />
//         </group>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Seat2_Palette001_0.geometry}
//           material={materials['Palette.001']}
//           position={[-26.871, 8.702, 58.969]}
//           rotation={[-3.128, -0.392, -2.972]}
//           scale={[0.68, 0.68, 0.604]}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload('/models/lowpoly_desk_and_monitor.glb');
