/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: GeniusPilot2016 (https://sketchfab.com/GeniusPilot2016)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fluorescent-fixture-fc054b134cd94311802b6a5e90da8588
Title: Fluorescent Fixture
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { angleToRadian } from '../../utils/angle';

export function LightModel(props) {
  const { nodes, materials } = useGLTF('/models/fluorescent_fixture.glb');
  return (
    <group
      {...props}
      dispose={null}
      position={[2,10, -2]}
      rotation={[0, 0, angleToRadian(180)]}
      scale={[3.5,0.5,3.5]}
    >
      <group
        position={[0.5, 0.06, 0.498]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, 0.1, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.corner}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.reflector}
        />
      </group>
      <group
        position={[0.086, 0.061, 0.498]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 0.889, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.fluorescent_tube}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.metal_base}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/fluorescent_fixture.glb');
