/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SugarSatea (https://sketchfab.com/SugarSatea)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/simple-pc-mouse-4a8fcd93c882402cab7d2d6458855ac5
Title: Simple PC Mouse
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { angleToRadian } from '../../utils/angle'

export function MouseModel(props) {
  const { nodes, materials } = useGLTF('/models/simple_pc_mouse.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Mouse.001']}
        scale={1}
        position={[2.3,2.9,2]}
        rotation={[0,-angleToRadian(35),0]}
      />
    </group>
  )
}

useGLTF.preload('/models/simple_pc_mouse.glb')
