/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: radioape (https://sketchfab.com/radioape)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/white-feature-phone-with-buttons-dce3b8b25f66495986e57374a80bd77e
Title: White feature phone with buttons
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { angleToRadian } from '../../utils/angle';

export function PhoneModel(props) {
  const { nodes, materials } = useGLTF(
    '/models/white_feature_phone_with_buttons.glb'
  );
  return (
    <group
      {...props}
      dispose={null}
      position={[3.4, 3, 2.5]}
      rotation={[0, -angleToRadian(115), 0]}
      scale={2}
    >
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002__0.geometry}
            material={materials['Scene_-_Root']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002__0.geometry}
            material={materials['Scene_-_Root']}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/white_feature_phone_with_buttons.glb');
