/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anom Purple Modelling (https://sketchfab.com/Anom404)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/file-shelf-adcc1ab47d7c45ff9d08e0af2815458b
Title: File Shelf
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function ShelfModel(props) {
  const { nodes, materials } = useGLTF('/models/file_shelf.glb');
  return (
    <group
      {...props}
      dispose={null}
      position={[-7.5, 0, -10]}
      rotation={[0, Math.PI / 4, 0]}
      scale={3}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={16.308}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cubo003_Cubo003_baked_0.geometry}
            material={materials['Cubo.003_baked']}
            position={[2.562, 5.655, -1.356]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/file_shelf.glb');
